# Generated by Django 3.1.2 on 2020-11-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('nom_admin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nb_client', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Piece_detachee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=7)),
                ('marque', models.CharField(max_length=100)),
                ('type_voiture', models.CharField(max_length=100)),
                ('date_arrivee', models.DateField()),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_form.client')),
            ],
        ),
        migrations.CreateModel(
            name='Reparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarque_technicien', models.TextField()),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('duree', models.DurationField(blank=True)),
                ('pieces_detachees', models.ManyToManyField(related_name='reparations', to='bdd_form.Piece_detachee')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_form.voiture')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_form.commune'),
        ),
    ]
