# Generated by Django 3.1.2 on 2020-11-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='date_arrivee',
            field=models.DateField(auto_now_add=True),
        ),
    ]
