# Generated by Django 3.1.2 on 2020-11-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd_form', '0002_auto_20201113_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='kilometrage',
            field=models.IntegerField(default=0),
        ),
    ]
