# Generated by Django 3.1.2 on 2020-12-04 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd_form', '0004_reparation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 4, 4, 32, 46, 434698)),
        ),
    ]
