# Generated by Django 3.1.2 on 2020-12-04 04:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bdd_form', '0005_auto_20201204_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparation',
            name='technicien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bdd_form.technicien'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reparation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
